### ISSUE TITLE
[1.3] Disabling Encounter Rate Disables Sirens

### ISSUE THREAD

**Issue by Dimlhugion** [gameboy9/FF4FabulGauntlet#12]
Setting the encounter rate to 0 in the options prevents you from using Sirens

**Comment by gameboy9** [comment]
I'll be taking a look at this.  I saw this with another streamer.  I may have to set the encounter rate to something like 1/9999 or something ridiculous like that.

**Comment by gameboy9** [comment]
This has been taken care of in version 2.0 with a 1/10000 encounter rate replacing the 0 rate.  This will enable the sirens for use.  It will be very unlikely to get a random encounter unless you try to find one deliberately.
