### ISSUE TITLE
Can't create a 2.0 seed 

### ISSUE THREAD

**Issue by TheBuffalax** [gameboy9/FF4FabulGauntlet#14]
I get this error message when trying to create a new seed. 

![error](https://user-images.githubusercontent.com/22268187/153719925-c28b6821-5318-4812-9810-52ee30e7f94c.png)

**Comment by TheBuffalax** [comment]
i just think it's where it says Map_20020 - Bad. i only have a Map-20020 folder there and nothing with the  - Bad tag on it

**Comment by gameboy9** [comment]
Please redownload at the same location; I removed the "- Bad" and "- Good" folders that this error is referring to.

My bad for the error.  Please reopen if there are further issues.

**Comment by gameboy9** [comment]
You can also work around this by searching for the "- Bad" and "- Good" folders and deleting them.

**Comment by TheBuffalax** [comment]
i got it to work. i have been overwriting the files in the folder for each new release. deleting the whole folder and copying over 2.0 did the trick. thanks!
