### ISSUE TITLE
Rydia learns Firaga instead of Fira

### ISSUE THREAD

**Issue by Fleury14** [gameboy9/FF4FabulGauntlet#3]
Where Rydia would expectedly learn Fira (nested around the other -ara spells) she instead learns Firaga.

![rydiafiraga](https://user-images.githubusercontent.com/29141727/137098323-6357167d-3272-4b3e-9170-110672c19981.PNG)

Appreciate the work, this has been a blast to play!

**Comment by gameboy9** [comment]
Effective on the next release (probably 0.3) Rydia will learn Fira (instead of Firaga) at level 22.

Thanks for giving this a try and reporting the issue!  :)
