### ISSUE TITLE
Barnabas-Z appearing in a non-boss fight

### ISSUE THREAD

**Issue by princedarian22** [gameboy9/FF4FabulGauntlet#4]
My apologies if this is intended, he hits 2 people for about 1500 then self destructs.

![Fabul Gaunlet BarnabZ](https://user-images.githubusercontent.com/13081645/137597953-7ec28a06-d149-4e61-a94d-3b9d0707b62f.png)

**Comment by gameboy9** [comment]
It is in fact intentional for Barnabas-Z to show up randomly.  At least for now.  If it turns out that it's going to be continuously too difficult, we'll revisit.
